const NODE_ENVS = {
  DEVELOPMENT: 'development',
  PRODUCTION: 'production',
};

const POSTGRESQL_ERROR_CODES = {
  INVALID_CATALOG_NAME: '3D000'
};

const HTTP_STATUS_CODES = {
  AUTH_FAIL: 401
};

module.exports = {
  NODE_ENVS,
  POSTGRESQL_ERROR_CODES,
  HTTP_STATUS_CODES
};
